name = "tomato-web"
compatibility_date = "2024-12-01"

[env.production]
name = "tomato-web"
workers_dev = false
routes = [
  { pattern = "hudongju.net/*", zone_name = "hudongju.net" },
  { pattern = "www.hudongju.net/*", zone_name = "hudongju.net" }
]

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
